### ISSUE TITLE
1-x-stable tests fail

### ISSUE THREAD

**Issue by utilum** [resque/resque#1312] opened 2015-07-04 00:49 UTC
Here's what I see:

```
$ bundle exec rake test --trace
** Invoke test (first_time)
** Execute test
/home/utilum/.rbenv/versions/2.2.0/bin/ruby -I"lib:test:lib"  "/home/utilum/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/rake_test_loader.rb" "test/airbrake_test.rb" "test/failure_base_test.rb" "test/job_hooks_test.rb" "test/job_plugins_test.rb" "test/logging_test.rb" "test/plugin_test.rb" "test/resque-web_test.rb" "test/resque_failure_redis_test.rb" "test/resque_hook_test.rb" "test/resque_test.rb" "test/worker_test.rb" 
/usr/local/bin/redis-server
Starting redis for testing at localhost:9736...
/home/utilum/code/resque_clean/test/test_helper.rb:67:in `require': cannot load such file -- test/unit (LoadError)
  from /home/utilum/code/resque_clean/test/test_helper.rb:67:in `context'
  from /home/utilum/code/resque_clean/test/airbrake_test.rb:12:in `<top (required)>'
  from /home/utilum/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/rake_test_loader.rb:15:in `require'
  from /home/utilum/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/rake_test_loader.rb:15:in `block in <main>'
  from /home/utilum/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/rake_test_loader.rb:4:in `select'
  from /home/utilum/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
Command failed with status (1): [ruby -I"lib:test:lib"  "/home/utilum/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/rake_test_loader.rb" "test/airbrake_test.rb" "test/failure_base_test.rb" "test/job_hooks_test.rb" "test/job_plugins_test.rb" "test/logging_test.rb" "test/plugin_test.rb" "test/resque-web_test.rb" "test/resque_failure_redis_test.rb" "test/resque_hook_test.rb" "test/resque_test.rb" "test/worker_test.rb" ]
/home/utilum/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/testtask.rb:108:in `block (3 levels) in define'
/home/utilum/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/file_utils.rb:57:in `call'
/home/utilum/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/file_utils.rb:57:in `sh'
/home/utilum/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/file_utils_ext.rb:37:in `sh'
/home/utilum/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/file_utils.rb:96:in `ruby'
/home/utilum/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/file_utils_ext.rb:37:in `ruby'
/home/utilum/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/testtask.rb:104:in `block (2 levels) in define'
/home/utilum/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/file_utils_ext.rb:58:in `verbose'
/home/utilum/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/testtask.rb:100:in `block in define'
/home/utilum/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/home/utilum/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/home/utilum/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/home/utilum/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/home/utilum/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/home/utilum/.rbenv/versions/2.2.0/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/utilum/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/home/utilum/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/home/utilum/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/home/utilum/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/home/utilum/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/home/utilum/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/home/utilum/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/home/utilum/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/home/utilum/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/home/utilum/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/home/utilum/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/home/utilum/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/home/utilum/.rbenv/versions/2.2.0/bin/rake:23:in `load'
/home/utilum/.rbenv/versions/2.2.0/bin/rake:23:in `<main>'
Tasks: TOP => test
```

**Comment by utilum** [comment] 2015-07-07 11:03
And now I see that master branch returns some 50 errors. Is this as expected at this stage?

**Comment by lukeasrodgers** [comment] 2015-08-11 17:01
I can't reproduce that failure (though I do get a single, unrelated spec failures with ruby 2.1.x), though I'm using rvm so possibly it's a rbenv-related issue.

**Comment by lukeasrodgers** [comment] 2015-08-13 21:48
Should be fixed as of https://github.com/resque/resque/pull/1322

**Closed** 2015-08-13 21:49 UTC
