### ISSUE TITLE
Tracking time between enqueue und performed

### ISSUE THREAD

**Issue by mojovski** [resque/resque#1340] opened 2015-10-19 22:13 UTC
Hi I would like to track the time my system needs to process the tasks.
This means I need the time elapsed between a task has been scheduled (enqueued) and finished (on after perform).

Intuitively I would store the start time along with the arguments of a task and after the task is finished store the passed time with the queue value persistently in redis.

Is there a way to do this with Resque? Maybe with a custom plugin?

Thanks alot!

**Comment by gaustin** [comment] 2015-10-20 17:24
We did something along these lines by adding the enqueued time as an extra argument to all jobs. Then our base job class (with an after_perform hook) writes out metrics based on that and when the job actually completes.

**Comment by mojovski** [comment] 2015-10-20 19:32
great, so where can I see these metrics or how can I access them? :) Could you give me a hint on some line in the code?

Thanks alot!

**Comment by steveklabnik** [comment] 2016-01-12 00:24
This is the motivation for https://github.com/resque/resque/issues/552, so closing as a duplicate of that.

**Closed by steveklabnik** 2016-01-12 00:24 UTC
