### ISSUE TITLE
redis time check at resque init throws Errno::ECONNREFUSED

### ISSUE THREAD

**Issue by timsatterfield** [resque/resque#1552] opened 2017-03-13 18:39 UTC
https://github.com/resque/resque/commit/a3c2ae16022f6f049174128be65c7c1a2c71ff6c

Using v1.27.2
Does not repro in v1.27.0.

Get this exception on startup

```
/usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:345:in `rescue in establish_connection': Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED) (Redis::CannotConnectError)
  from /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:331:in `establish_connection'
  from /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:101:in `block in connect'
  from /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:293:in `with_reconnect'
  from /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:100:in `connect'
  from /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:364:in `ensure_connected'
  from /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:221:in `block in process'
  from /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:306:in `logging'
  from /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:220:in `process'
  from /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:120:in `call'
  from /usr/local/bundle/gems/redis-3.3.3/lib/redis.rb:351:in `block in time'
  from /usr/local/bundle/gems/redis-3.3.3/lib/redis.rb:58:in `block in synchronize'
  from /usr/local/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
  from /usr/local/bundle/gems/redis-3.3.3/lib/redis.rb:58:in `synchronize'
  from /usr/local/bundle/gems/redis-3.3.3/lib/redis.rb:350:in `time'
  from /usr/local/bundle/gems/redis-namespace-1.5.3/lib/redis/namespace.rb:435:in `call_with_namespace'
  from /usr/local/bundle/gems/redis-namespace-1.5.3/lib/redis/namespace.rb:321:in `method_missing'
  from /usr/local/bundle/gems/resque-1.27.2/lib/resque/data_store.rb:100:in `redis_time_available?'
  from /usr/local/bundle/gems/resque-1.27.2/lib/resque/data_store.rb:15:in `initialize'
  from /usr/local/bundle/gems/resque-1.27.2/lib/resque.rb:125:in `new'
  from /usr/local/bundle/gems/resque-1.27.2/lib/resque.rb:125:in `redis='
  from /usr/local/bundle/gems/resque-web-0.0.9/config/initializers/resque_config.rb:4:in `<top (required)>'
  from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
  from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
  from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
  from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
  from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:652:in `block in load_config_initializer'
  from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
  from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:651:in `load_config_initializer'
  from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
  from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `each'
  from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `block in <class:Engine>'
  from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
  from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
  from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
  from /usr/local/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
  from /usr/local/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  from /usr/local/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
  from /usr/local/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
  from /usr/local/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
  from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
  from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
  from /usr/local/lib/ruby/2.3.0/tsort.rb:415:in `call'
  from /usr/local/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
  from /usr/local/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
  from /usr/local/lib/ruby/2.3.0/tsort.rb:347:in `each'
  from /usr/local/lib/ruby/2.3.0/tsort.rb:347:in `call'
  from /usr/local/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
  from /usr/local/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
  from /usr/local/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
  from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
  from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
  from /app/config/environment.rb:5:in `<top (required)>'
  from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
  from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
  from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
  from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
  from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/application.rb:328:in `require_environment!'
  from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:142:in `require_application_and_environment!'
  from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:67:in `console'
  from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
  from bin/rails:4:in `require'
  from bin/rails:4:in `<main>'
```

Redis connection is defined in the redis.rb init file like:
```
$redis = Redis.new(url: ENV["REDIS_URL"])
```

Somehow in this behavior, the default 127.0.0.1:6379 is used instead of the redis_url ENV value.

**Comment by bibendi** [comment] 2017-03-29 18:48
You should not call any redis commands at application boot.

```

/bundle/2.3/gems/redis-3.3.3/lib/redis/client.rb:345:in `rescue in establish_connection': Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED) (Redis::CannotConnectError)
	from /bundle/2.3/gems/redis-3.3.3/lib/redis/client.rb:331:in `establish_connection'
	from /bundle/2.3/gems/redis-3.3.3/lib/redis/client.rb:101:in `block in connect'
	from /bundle/2.3/gems/redis-3.3.3/lib/redis/client.rb:293:in `with_reconnect'
	from /bundle/2.3/gems/redis-3.3.3/lib/redis/client.rb:100:in `connect'
	from /bundle/2.3/gems/redis-3.3.3/lib/redis/client.rb:364:in `ensure_connected'
	from /bundle/2.3/gems/redis-3.3.3/lib/redis/client.rb:221:in `block in process'
	from /bundle/2.3/gems/redis-3.3.3/lib/redis/client.rb:306:in `logging'
	from /bundle/2.3/gems/redis-3.3.3/lib/redis/client.rb:220:in `process'
	from /bundle/2.3/gems/redis-3.3.3/lib/redis/client.rb:120:in `call'
	from /bundle/2.3/gems/redis-3.3.3/lib/redis.rb:351:in `block in time'
	from /bundle/2.3/gems/redis-3.3.3/lib/redis.rb:58:in `block in synchronize'
	from /usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	from /bundle/2.3/gems/redis-3.3.3/lib/redis.rb:58:in `synchronize'
	from /bundle/2.3/gems/redis-3.3.3/lib/redis.rb:350:in `time'
	from /bundle/2.3/gems/redis-namespace-1.5.3/lib/redis/namespace.rb:435:in `call_with_namespace'
	from /bundle/2.3/gems/redis-namespace-1.5.3/lib/redis/namespace.rb:321:in `method_missing'
	from /bundle/2.3/gems/resque-1.27.2/lib/resque/data_store.rb:100:in `redis_time_available?'
	from /bundle/2.3/gems/resque-1.27.2/lib/resque/data_store.rb:15:in `initialize'
	from /bundle/2.3/gems/resque-1.27.2/lib/resque.rb:125:in `new'
	from /bundle/2.3/gems/resque-1.27.2/lib/resque.rb:125:in `redis='
	from /bundle/2.3/gems/resque-web-0.0.9/config/initializers/resque_config.rb:4:in `<top (required)>'
```

**Comment by jakewilkins** [comment] 2017-04-10 18:47
This causes an issue deploying to Heroku - asset compilation loads the rails environment but the `REDIS_URL` ENV var isn't set.

on `v1.27.1`, this is fine since no commands are executed. on `v1.27.2` this cause asset compilation to fail with the above error.

**Comment by chrisccerami** [comment] 2017-04-10 18:53
I just merged #1545 into master. Could you try pointing your Gemfile there and let me know if that resolves the problem for you? If so, I'll release a new version either today or tomorrow.

**Comment by jakewilkins** [comment] 2017-04-10 18:57
Awesome! we're trying it & we'll let you know.

Thanks! 💕 ❤️ 😻 💗

**Comment by jakewilkins** [comment] 2017-04-10 19:04
Confirmed that our build does not fail using master.

**Comment by chrisccerami** [comment] 2017-04-10 19:15
Thanks, I'll try to release as soon as I get a chance.

**Comment by chrisccerami** [comment] 2017-04-10 23:47
1.27.3 has now been released with this fix. I'm going to close this, but feel free to reopen it if you still have issues.

**Closed by chrisccerami** 2017-04-10 23:47 UTC
