### ISSUE TITLE
Resque 2 breakes eager loading in workers

### ISSUE THREAD

**Issue by micke** [resque/resque#1698] opened 2019-12-12 11:40 UTC
In #1597 resque started respecting the `eager_load` config in rails, which sounds great!
The problem is that `eager_load` is always false when rails is running in rake because of rails/rails#11389

This breaks applications that require that all classes are loaded.

**Comment by jiikko** [comment] 2019-12-18 03:35
duplicate of https://github.com/resque/resque/issues/1680

**Comment by wwahammy** [comment] 2020-01-04 20:23
Wanted to let folks know that an option for using eager loading in Rake tasks was recently merged to Rails with rails/rails#28209

**Closed** 2020-01-06 23:19 UTC
