### ISSUE TITLE
Resque.inline = true issue

### ISSUE THREAD

**Issue by barmstrong** [resque/resque#753] opened 2012-11-19 20:36 UTC
I have `Resque.inline = true` set but it doesn't seem to have the desired effect.  Read elsewhere people saw conflicts with `resque-scheduler` which we're also using.  I tried downgrading resque to 1.20.0 and a few other things - no luck.

Have reverted back to this for now.

```ruby
  if Rails.env.production?
      Resque.enqueue(SampleJob, t.id)
    else
      SampleJob.perform(t.id)
   end
```

We're using the following:

```ruby
gem 'resque',                        '1.23.0'
gem 'resque_mailer',                 '2.1.0'
gem 'resque-scheduler',              '2.0.0', require: 'resque_scheduler'
gem 'resque-failed-job-mailer',      '0.0.1', require: 'resque_failed_job_mailer'
gem 'resque-retry',                  '1.0.0'
```

Anyone else seeing issues?

**Comment by tute** [comment] 2015-02-11 22:46
Scheduler says it respects `inline` (https://github.com/resque/resque-scheduler/blob/master/lib/resque/scheduler/delaying_extensions.rb#L20-L43), but we are seeing something similar with this combination. Will share what we find.

**Comment by tute** [comment] 2015-02-12 16:16
I couldn't debug inside the gems, but I changed my specs to use `expect to have_queued`, which is good enough for my application.

**Comment by raquelhosein** [comment] 2015-12-15 17:46
Hey guys is this still an issue?

**Comment by steveklabnik** [comment] 2016-01-12 00:07
If anyone is still seeing this, could you help me reproduce it somehow?

**Comment by lukeasrodgers** [comment] 2016-02-08 20:21
We use `resque_inline` in our codebase as well as resque scheduler (v 4.0.0) and don't seem to have any issues.

**Comment by steveklabnik** [comment] 2016-02-08 21:36
Okay, I'm going to close this until someone finds a reproduction. Thank you!

**Closed by steveklabnik** 2016-02-08 21:36 UTC
Labels: Bug, Needs reproduction

**Comment by hieuk09** [comment] 2017-02-06 09:40
Hi @steveklabnik, I come across this bug when using rspec and resque together with zeus. I created a  sample repository [here](https://github.com/hieuk09/resque-issue-753-sample/blob/master/README.md). It would be great if you can take a look.

**Comment by chrisccerami** [comment] 2017-02-06 10:51
In the sample repo, the removal of resque-scheulder doesn't resolve the issue. I'm not familiar with zeus, but it seems like the conflict is there. It also doesn't really seem related to the above issue, which was with the functioning of Resque.inline

**Comment by hieuk09** [comment] 2017-02-06 17:24
Thanks for checking, @chrisccerami. I looked more into it and figured out the root cause. 

You're right, this is not related to this issue or resque. Another piece of my code adds a monkey-patch to resque to ensure that the job is only enqueued after an activerecord transaction is finished. In zeus, to make the request faster, db transactions are always open, so the job isn't enqueued.
