### ISSUE TITLE
Broken pipe issue

### ISSUE THREAD

**Issue by GaganMeesala** [resque/resque#1628] opened 2018-05-07 04:49 UTC
bundle exec unicorn -p 3001 -E production -c  ~/asp/config/unicorn.rb

PIDFILE=./resque.pid BACKGROUND=yes RAILS_ENV=production bundle exec rake resque:workers QUEUE='*' COUNT='5'

PIDFILE=./resque-scheduler.pid BACKGROUND=yes RAILS_ENV=production bundle exec rake resque:scheduler

bundle exec unicorn -p 3000 -E production -c ~/gsp-api/config/unicorn.rb

Error:

**RESPONSE={"code":99,"result":"Broken pipe @ io_write - \u003cSTDOUT\u003e "}**

Please help out of this issue, since so many days I'm facing this issue, not able to find the issue.

@defunkt @hone

**Comment by Fun32secg32** [comment] 2018-07-13 22:08
[Araştırma yaptığım sayfalarda sürekli çerez linkleri oluşmaya başladı ne kadar güvenlik önlemleri aldimsa yeni de bu sorunlar olmaya devam etti önce sistem çöktü daha sonra cihazim bozuldu tekrar cihaz aldım hesaplarimi tekrar kurmaya çalışıyorum 


wp225_en.pdf](https://github.com/resque/resque/files/2194294/wp225_en.pdf)

**Comment by Fun32secg32** [comment] 2018-07-13 22:38
Duplicate of #1643 #1635 @defunkt 

- [ ] [https://com.plus.googlefundasecgin
`[APG-AuditReports2015.pdf](https://github.com/resque/resque/files/2194371/APG-AuditReports2015.pdf)`
](url)

**Comment by TundraGreen** [comment] 2018-09-12 14:13
We are having the same problem:
    Exception
        Errno::EPIPE
    Error
        Broken pipe @ io_write - \<STDERR\>
I don't have any clues to add about the source. From looking at other similar complaints it might have to do with some Gem inconsistencies, but we are not using any of the Gems that people reported problems with.

**Comment by rafaelfranca** [comment] 2018-09-12 21:35
Can you please provide a sample application that reproduces the error?

**Comment by rafaelfranca** [comment] 2018-09-20 16:52
So unfortunately there is nothing se can do with the information provided. If we can't reproduce or even investigate the cause of the issue, there is no way to us to know the solution.

Let us know if you can reproduce this error consistently or if you know the cause of it and we will reopen the issue.

**Closed by rafaelfranca** 2018-09-20 16:52 UTC

**Comment by TundraGreen** [comment] 2018-09-20 17:38
I agree with your assessment. One cannot find an error if it is not reproducible. The only thing I will add here in case it might be useful to others is the following.
We found that the same error occurred using sidkiq instead of resque. At the moment it appears that it may be connected the the interaction between [ resque | sidekiq ] and redis. We were running a 2.x version of redis. We have  upgraded redis to 4.x and will know in a day or two if it fixed the problem.
